"""Add Order table

Revision ID: 8df7f07325f8
Revises: 2836c87a81d9
Create Date: 2024-09-23 22:02:38.395276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8df7f07325f8"
down_revision: Union[str, None] = "2836c87a81d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_items",
        sa.Column("oid", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления записи",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания записи",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.oid"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.oid"],
        ),
        sa.PrimaryKeyConstraint("oid"),
    )
    op.create_unique_constraint(None, "orders", ["oid"])
    op.create_unique_constraint(None, "products", ["oid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="unique")
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_table("order_items")
    # ### end Alembic commands ###
